version: "3"
services:

  mongo:
    image: mongo
    ports:
      - "27017"
    networks:
      - backend
  fbtrex:
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile

networks:
  backend:
